### ISSUE TITLE
Support external proxy users

### ISSUE THREAD

**Issue by sebastient** [jpxthu/RCLootCouncil_EPGP_Classic#1]
The EPGP mod supports external (out of guild) users by having a proxy which is in guild along with a public note "ext:MAIN" which links to the main.  It would be nice if RCLootCouncil EPGP would play nice with EPGP Classic on this feature.

**Comment by jpxthu** [comment]
You are right. RCEPGP didn't support it. I will fix this later.

**Comment by jpxthu** [comment]
Fixed in EPGP-Classic v1.4.9. Please upgrade to the newest version and have a try.

**Comment by sebastient** [comment]
Works as expected now, thank you.
