### ISSUE TITLE
Any chance for an update for TBC?

### ISSUE THREAD

**Issue by bagstone** [jpxthu/RCLootCouncil_EPGP_Classic#2]
RCLC as well as EPGP have been updated for TBC and are working, just this addon isn't, but it's the brilliant missing link between the two... any chance for a TBC working version? :) Thanks!

**Comment by jpxthu** [comment]
@bagstone I had a simple test before. It seems RCLC-EPGP worked well after EPGP updated. Is there any problems on these addons? Let me know and I will fix it.

Just remember to update EPGP TBC and load expired addons. I will update the version later.

**Comment by bagstone** [comment]
Oh you're right, I had a guild-modified version which is why it didn't work. The Curseforge version does work, brilliant! Thanks again! Gonna close this then ;)
